/
SET SERVEROUTPUT ON
DECLARE
    CURSOR TBL_SPACE_CUR IS 
    SELECT *
    FROM DBA_USERS
    WHERE USERNAME LIKE '%&1%'
    ORDER BY 1;

    FILA_VAR TBL_SPACE_CUR%ROWTYPE;

    LOG_INFO VARCHAR(255);
    TABLESPACE_INFO VARCHAR(255);
BEGIN

    LOG_INFO := RPAD(LPAD(' SCRIPT FIND TABLASPACE ', 50, '#'), 75, '#');
    DBMS_OUTPUT.PUT_LINE(LOG_INFO);
    
    LOG_INFO := RPAD('USER NAME', 25, ' ') || RPAD('DEFAULT TABLESPACE', 25, ' ') || RPAD('TEMPORARY TABLESPACE', 25, ' ');
    DBMS_OUTPUT.PUT_LINE(LOG_INFO);

    FOR FILA_VAR IN TBL_SPACE_CUR
    LOOP
        LOG_INFO := RPAD(FILA_VAR.USERNAME, 25, ' ')  || RPAD(FILA_VAR.DEFAULT_TABLESPACE, 25, ' ')
                        || RPAD(FILA_VAR.TEMPORARY_TABLESPACE, 25, ' ');
        DBMS_OUTPUT.PUT_LINE(LOG_INFO);
        TABLESPACE_INFO := '[' || FILA_VAR.DEFAULT_TABLESPACE || ';' || FILA_VAR.TEMPORARY_TABLESPACE || ']';
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(TABLESPACE_INFO);
    DBMS_OUTPUT.PUT_LINE('[[[OK]]]');
EXCEPTION
WHEN OTHERS THEN

    DBMS_OUTPUT.PUT_LINE('[[[NOK]]]');
    DBMS_OUTPUT.PUT_LINE('ERROR CODE: ' || SQLCODE || ' DETAIL: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('BACKTRACE: ' || DBMS_UTILITY.format_error_backtrace);
END;
/
EXIT;
